tileSource = {
    "bottom,start": {
        "fileName": "bottom,start",
        "north": false,
        "east": false,
        "south": true,
        "west": false,
        "others": "start",
        "map": {
            "5,3": "south,west,sw", //exit - right
            "5,2": "north,east,south,se", //Exit - left
            "4,4": "north,west,nw", //right corner
            "3,4": "south,west,sw,nw", //right wall
            "2,3": "south,se", //jetty - tip
            "3,3": "north,east,south,sw", //jetty - middle
            "4,3": "north,east,west,ne", //jetty - bottom
            "4,2": "east,south,west,ne", //doorway
            "4,1": "east",//corner
        }
    },
    "bottom,empty": {
        "fileName": "bottom,empty",
        "north": false,
        "east": false,
        "south": true,
        "west": false,
        "others": "empty",
        "map": {
          "1,1": "east,south",
          "1,2": "east,south,west",
          "1,3": "east,south,west",
          "1,4": "south,west",
          "2,1": "north,east,south",
          "2,2": "north,east,south,west",
          "2,3": "north,east,south,west",
          "2,4": "north,south,west",
          "3,1": "north,east,south",
          "3,2": "north,east,south,west",
          "3,3": "north,east,south,west",
          "3,4": "north,south,west",
          "4,1": "north,east",
          "4,2": "north,east,south,west",
          "4,3": "north,east,south,west",
          "4,4": "north,west",
          "5,2": "north,east,south",
          "5,3": "north,south,west",
        }
    },
    "bottom,hall": {
        "fileName": "bottom,hall",
        "north": false,
        "east": false,
        "south": true,
        "west": false,
        "others": "hall",
        "map": {

        }
    },
    "bottom,deadend": {
        "fileName": "bottom,deadend",
        "north": false,
        "east": false,
        "south": true,
        "west": false,
        "others": "deadend",
        "map": {

        }
    },
    "bottom,room": {
        "fileName": "bottom,room",
        "north": false,
        "east": false,
        "south": true,
        "west": false,
        "others": "room",
        "map": {

        }
    },
    "bottom,room1": {
        "fileName": "bottom,room1",
        "north": false,
        "east": false,
        "south": true,
        "west": false,
        "others": "room",
        "map": {

        }
    },
    "bottom,room2": {
        "fileName": "bottom,room2",
        "north": false,
        "east": false,
        "south": true,
        "west": false,
        "others": "room",
        "map": {
          "0,1": ",east",
          "0,2": "east,west,se",
          "0,3": "east,south,west",
          "0,4": "east,west,se,sw",
          "0,5": "south,west",
          "1,3": "north,south,ne,nw,se,sw",
          "1,5": "north,south,nw,sw",
          "2,2": "east,ne,se,sw",
          "2,3": "north,east,south,west",
          "2,4": "east,west,ne,se,sw,nw",
          "2,5": "north,south,west",
          "3,0": "east,south,se",
          "3,1": "south,west,ne,se,sw",
          "3,3": "north,south,ne,se,sw,nw",
          "3,5": "north,south,sw,nw",
          "4,0": "north,east,ne",
          "4,1": "north,east,west,se,nw",
          "4,2": "east,south,west,ne,se,nw",
          "4,3": "north,east,south,west,sw,se",
          "4,4": "east,south,west,ne,se,sw,nw",
          "4,5": "north,south,west,sw",
          "5,2": "north,east,south,ne,se,sw,nw",
          "5,3": "north,south,west,ne,se,sw,nw",
          "5,4": "north,east,ne,nw",
          "5,5": "north,west,nw",
        }
    },
    "bottom,altar": {
        "fileName": "bottom,altar",
        "north": false,
        "east": false,
        "south": true,
        "west": false,
        "others": "altar",
        "map": {

        }
    },
    "bottom,right,crooked,passage1": {
        "fileName": "bottom,right,crooked,passage1",
        "north": false,
        "east": true,
        "south": true,
        "west": false,
        "others": "crooked,passage",
        "map": {
          "1,1": "east,south",
          "1,2": "south,west",
          "1,4": ",south",
          "2,1": "north,east",
          "2,2": "north,south,west",
          "2,4": "north,east,south",
          "2,5": "east,south,west",
          "3,2": "north,south",
          "3,4": "north,east,south",
          "3,5": "north,east,west",
          "4,1": ",east",
          "4,2": "north,east,south,west",
          "4,3": "east,south,west",
          "4,4": "north,west",
          "5,2": "north,east,south",
          "5,3": "north,south,west"
        }
    },
    "bottom,right,statue": {
        "fileName": "bottom,right,statue",
        "north": false,
        "east": true,
        "south": true,
        "west": false,
        "others": "statue",
        "map": {
          "1,1": "east,south",
          "1,2": "east,south,west",
          "1,3": "east,south,west",
          "1,4": "south,west",
          "2,1": "north,east,south",
          "2,2": "north,east,south,west",
          "2,3": "north,east,south,west",
          "2,4": "north,east,south,west",
          "2,5": "east,south,west",
          "3,1": "north,east,south",
          "3,2": "north,east,south,west",
          "3,3": "north,east,south,west",
          "3,4": "north,east,south,west",
          "3,5": "north,east,west",
          "4,1": "north,east",
          "4,2": "north,east,south,west",
          "4,3": "north,east,south,west",
          "4,4": "north,west",
          "5,2": "north,east,south",
          "5,3": "north,south,west",
        }
    },
    "bottom,right,stairs": {
        "fileName": "bottom,right,stairs",
        "north": false,
        "east": true,
        "south": true,
        "west": false,
        "others": "stairs",
        "map": {
          "1,1": "east,south",
          "1,2": "east,west",
          "1,3": "west",
          "2,1": "north,south",
          "2,5": "east,south",
          "3,1": "north,south",
          "3,3": "east,south",
          "3,4": "east,south,west",
          "3,5": "north,east,west",
          "4,1": "north,east",
          "4,2": "east,south,west",
          "4,3": "north,east,south,west",
          "4,4": "north,west",
          "5,2": "north,east,south",
          "5,3": "north,south,west",
        }
    },
    "bottom,right,stairs1": {
        "fileName": "bottom,right,stairs1",
        "north": false,
        "east": true,
        "south": true,
        "west": false,
        "others": "stairs",
        "map": {
          "1,1": "east,south",
          "1,2": "east,west",
          "1,3": "east,west",
          "1,4": "south,west",
          "2,1": "north,south",
          "2,4": "north,south",
          "2,5": "east,south",
          "3,1": "north,south",
          "3,4": "north,east",
          "3,5": "north,east,west",
          "4,1": "north,east",
          "4,2": "east,west",
          "4,3": "south,west",
          "5,2": "east,south",
          "5,3": "north,south,west",
        }
    },
    "bottom,right,tower,stairs": {
        "fileName": "bottom,right,tower,stairs",
        "north": false,
        "east": true,
        "south": true,
        "west": false,
        "others": "tower,stairs",
        "map": {
          "1,2": "east,south",
          "1,3": "south,west",
          "2,1": "east,south",
          "2,2": "north,east,west,south",
          "2,3": "north,east,west",
          "2,4": "west",
          "2,5": "east,south",
          "3,1": "north,east",
          "3,2": "north,east,south,west",
          "3,3": "east,south,west",
          "3,4": "east,south,west",
          "3,5": "north,east,south,west",
          "4,2": "north,east",
          "4,3": "north,east,south,west",
          "4,4": "north,east,south,west",
          "4,5": "north,south,west",
          "5,2": "east,south",
          "5,3": "north,east,south,west",
          "5,4": "north,east,west",
          "5,5": "north,west"
        }
    },
    "bottom,right,pool": {
        "fileName": "bottom,right,pool",
        "north": false,
        "east": true,
        "south": true,
        "west": false,
        "others": "pool",
        "map": {
          "0,0": "east,south,se",
          "0,1": "east,south,west,se,sw",
          "0,2": "east,south,west,se,sw",
          "0,3": "east,south,west,sw",
          "0,4": "west,sw",
          "1,0": "north,east,ne,se",
          "1,1": "north,east,south,west,ne,se,sw,nw",
          "1,2": "north,east,south,west,ne,se,sw,nw",
          "1,3": "north,south,west,ne,se,sw,nw",
          "2,0": "north,east,south,ne,se",
          "2,1": "north,east,south,west,ne,se,sw,nw",
          "2,2": "north,east,south,west",
          "2,3": "north,east,south,west,se,sw,nw",
          "2,4": "east,south,west,se,sw",
          "2,5": "east,south,west,se,sw",
          "3,0": "north,east,south,ne",
          "3,1": "north,east,west,ne,se,sw,nw",
          "3,2": "north,east,south,west,ne,se,sw,nw",
          "3,3": "north,east,south,west,ne,se,sw,nw",
          "3,4": "north,east,south,west,ne,sw,nw",
          "3,5": "north,east,west,ne,sw,nw",
          "4,0": "north,ne",
          "4,2": "north,east,south,ne,se,nw",
          "4,3": "north,east,south,west,ne,sw,nw",
          "4,4": "north,west,ne,se,sw,nw",
          "5,2": "north,east,south,ne,se",
          "5,3": "north,south,west,ne,sw,nw",
        }
    },
    "bottom,right,passage": {
        "fileName": "bottom,right,passage",
        "north": false,
        "east": true,
        "south": true,
        "west": false,
        "others": "passage",
        "map": {
          "2,2": "east,south",
          "2,3": "east,south,west",
          "2,4": "east,south,west",
          "2,5": "east,south,west",
          "3,2": "north,east,south",
          "3,3": "north,east,south,west",
          "3,4": "east,south,west",
          "3,5": "north,east,west",
          "4,2": "north,east,south",
          "4,3": "north,south,west",
          "5,2": "north,east,south",
          "5,3": "north,south,west",
        }
    },
    "bottom,right,passage1": {
        "fileName": "bottom,right,passage1",
        "north": false,
        "east": true,
        "south": true,
        "west": false,
        "others": "passage",
        "map": {
          "1,1": "east,south",
          "1,2": "south,west",
          "1,4": "south",
          "2,1": "north,east",
          "2,2": "north,east,west",
          "2,3": "east,west",
          "2,4": "north,east,south,west",
          "2,5": "east,south,west",
          "3,4": "north,east,south",
          "3,5": "north,east,west",
          "4,1": "east",
          "4,2": "east,south,west",
          "4,3": "east,south,west",
          "4,4": "north,west",
          "5,2": "north,east,south",
          "5,3": "north,south,west"
        }
    },
    "bottom,right,passage2": {
        "fileName": "bottom,right,passage2",
        "north": false,
        "east": true,
        "south": true,
        "west": false,
        "others": "passage",
        "map": {
          "2,2": "east,south",
          "2,3": "east,south,west",
          "2,4": "east,south,west",
          "2,5": "east,south,west",
          "3,2": "north,east,south",
          "3,3": "north,east,south,west",
          "3,4": "north,east,west",
          "3,5": "north,east,west",
          "4,2": "north,east,south",
          "4,3": "north,south,west",
          "5,2": "dd,east,south",
          "5,3": "north,south,west",
        }
    },
    "bottom,right,passage3": {
        "fileName": "bottom,right,passage3",
        "north": false,
        "east": true,
        "south": true,
        "west": false,
        "others": "passage,empty",
        "map": {
          "1,1": "east,south",
          "1,2": "east,south,west",
          "1,3": "east,south,west",
          "1,4": "south,west",
          "2,1": "north,east,south",
          "2,2": "north,east,south,west",
          "2,3": "north,east,south,west",
          "2,4": "north,east,south,west",
          "2,5": "east,south,west",
          "3,1": "north,east,south",
          "3,2": "north,east,south,west",
          "3,3": "north,east,south,west",
          "3,4": "north,east,south,west",
          "3,5": "north,east,west",
          "4,1": "north,east",
          "4,2": "north,east,south,west",
          "4,3": "north,east,south,west",
          "4,4": "north,west",
          "5,2": "north,east,south",
          "5,3": "north,south,west",
        }
    },
    "bottom,right,passage4": {
        "fileName": "bottom,right,passage4",
        "north": false,
        "east": true,
        "south": true,
        "west": false,
        "others": "passage",
        "map": {
          "1,1": "east,south",
          "1,2": "east,south,west",
          "1,3": "east,south,west",
          "1,4": "south,west",
          "2,1": "north,east,south",
          "2,2": "north,east,south,west",
          "2,3": "north,east,south,west",
          "2,4": "north,east,south,west",
          "2,5": "east,south,west",
          "3,1": "north,east,south",
          "3,2": "north,east,south,west",
          "3,3": "north,east,south,west",
          "3,4": "north,east,south,west",
          "3,5": "north,east,west",
          "4,1": "north,east",
          "4,2": "north,east,south,west",
          "4,3": "north,east,south,west",
          "4,4": "north,west",
          "5,2": "north,east,south",
          "5,3": "north,south,west",
        }
    },
    "bottom,right,passage5": {
        "fileName": "bottom,right,passage5",
        "north": false,
        "east": true,
        "south": true,
        "west": false,
        "others": "passage",
        "map": {
          "1,1": "east,south",
          "1,2": "east,west",
          "1,3": "east,west",
          "1,4": "south,west",
          "2,1": "north,south",
          "2,4": "north,south",
          "2,5": "east,south",
          "3,1": "north,south",
          "3,4": "north,east",
          "3,5": "north,east,west",
          "4,1": "north,east",
          "4,2": "east,west",
          "4,3": "south,west",
          "5,2": "east,south",
          "5,3": "north,south,west",
        }
    },
    "bottom,right,ornate": {
        "fileName": "bottom,right,ornate",
        "north": false,
        "east": true,
        "south": true,
        "west": false,
        "others": "ornate",
        "map": {
          "2,2": "east,south",
          "2,3": "east,south,west",
          "2,4": "east,south,west",
          "2,5": "east,south,west",
          "3,2": "north,east,south",
          "3,3": "north,east,south,west",
          "3,4": "east,west",
          "3,5": "north,east,west",
          "4,2": "north,east,south",
          "4,3": "north,south,west",
          "5,2": "north,east,south",
          "5,3": "north,south,west",
        }
    },
    "bottom,right,top,left,crossroad": {
        "fileName": "bottom,right,top,left,crossroad",
        "north": true,
        "east": true,
        "south": true,
        "west": true,
        "others": "crossroad",
        "map": {
          "0,2": "north,east,south",
          "0,3": "north,south,west",
          "1,2": "north,east,south",
          "1,3": "north,south,west",
          "2,0": "east,south,west",
          "2,1": "east,south,west",
          "2,2": "north,east,south,west",
          "2,3": "north,east,south,west",
          "2,4": "east,south,west",
          "2,5": "east,south,west",
          "3,0": "north,east,west",
          "3,1": "north,east,west",
          "3,2": "north,east,south,west",
          "3,3": "north,east,south,west",
          "3,4": "north,east,west",
          "3,5": "north,east,west",
          "4,2": "north,east,south",
          "4,3": "north,south,west",
          "5,2": "north,east,south",
          "5,3": "north,south,west",
        }
    },
    "bottom,right,top,left,crossroad1": {
        "fileName": "bottom,right,top,left,crossroad1",
        "north": true,
        "east": true,
        "south": true,
        "west": true,
        "others": "crossroad",
        "map": {
          "0,2": "north,east,south,ne,se,nw",//"north,east,ne",
          "0,3": "north,south,west,ne,sw", //"north,west,nw",
          "1,1": "east,south,ne,sw",
          "1,2": "north,east,west,ne,sw",
          "1,3": "north,east,west,se,nw",
          "1,4": "south,west,se,nw",
          "2,0": "east,south,west,ne,se,sw",
          "2,1": "north,south,west,ne,sw",
          "2,4": "north,east,south,se,nw",
          "2,5": "east,south,west,se,sw,nw",
          "3,0": "north,east,west,ne,nw",
          "3,1": "north,west,nw",
          "3,4": "north,east,ne",
          "3,5": "north,east,west,ne,nw",
          "5,2": "east,south,se",
          "5,3": "south,west,sw",
        }
    },
    "bottom,right,top,left,crossroad5": {
        "fileName": "bottom,right,top,left,crossroad5",
        "north": true,
        "east": true,
        "south": true,
        "west": true,
        "others": "crossroad",
        "map": {

        }
    },
    "bottom,right,top,left,crossroad6": {
        "fileName": "bottom,right,top,left,crossroad6",
        "north": true,
        "east": true,
        "south": true,
        "west": true,
        "others": "crossroad",
        "map": {

        }
    },
    "bottom,right,top,left,statue,crossroad": {
        "fileName": "bottom,right,top,left,statue,crossroad",
        "north": true,
        "east": true,
        "south": true,
        "west": true,
        "others": "statue,crossroad",
        "map": {
          "0,2": "north,east,south",
          "0,3": "north,south,west",
          "1,1": "east,south",
          "1,2": "north,east,west",
          "1,3": "north,east,west",
          "1,4": "south,west",
          "2,0": "east,south,west",
          "2,1": "north,south,west",
          "2,4": "north,east,south",
          "2,5": "east,south,west",
          "3,0": "north,east,west",
          "3,1": "north,south,west",
          "3,4": "north,east,south",
          "3,5": "north,east,west",
          "4,1": "north,east",
          "4,2": "east,south,west",
          "4,3": "east,south,west",
          "4,4": "north,west",
          "5,2": "north,east,south",
          "5,3": "north,south,west",
        }
    },
    "bottom,right,top,left,crooked,crossroad2": {
        "fileName": "bottom,right,top,left,crooked,crossroad2",
        "north": true,
        "east": true,
        "south": true,
        "west": true,
        "others": "crooked,crossroad",
        "map": {
          "0,2": "north,east,south",
          "0,3": "north,south,west",
          "1,1": "east,south",
          "1,2": "north,east,west",
          "1,3": "north,east,west",
          "1,4": "south,west",
          "2,0": "east,south,west",
          "2,1": "north,south,west",
          "2,4": "north,east",
          "2,5": "east,south,west",
          "3,0": "north,east,west",
          "3,1": "north,east,west",
          "3,2": "south,west",
          "3,5": "north,east",
          "4,2": "north,east,south",
          "4,3": "south,west",
          "5,2": "north,east,south",
          "5,3": "north,south,west",
        }
    },
    "bottom,right,top,left,deadend,crossroad": {
        "fileName": "bottom,right,top,left,deadend,crossroad",
        "north": true,
        "east": true,
        "south": true,
        "west": true,
        "others": "deadend,crossroad",
        "map": {

        }
    },
    "bottom,right,top,left,maze,crossroad": {
        "fileName": "bottom,right,top,left,maze,crossroad",
        "north": true,
        "east": true,
        "south": true,
        "west": true,
        "others": "maze,crossroad",
        "map": {
          "0,0": "south,east",
          "0,1": "east,west",
          "0,2": "north,east,west",
          "0,3": "north,east,west",
          "0,4": "east,west",
          "0,5": "west",
          "1,0": "north,east",
          "1,1": "south,west",
          "1,2": "east,south,",
          "1,3": "east,west",
          "1,4": "east,west",
          "1,5": "south,west",
          "2,0": "east,south,west",
          "2,1": "north,south,west",
          "2,2": "north,east",
          "2,3": "east,west",
          "2,4": "south,west",
          "2,5": "north,east,south",
          "3,0": "north,east,south,west",
          "3,1": "north,east,west",
          "3,2": "east,west",
          "3,3": "west",
          "3,4": "north,south",
          "3,5": "north,east,south",
          "4,0": "north,south",
          "4,1": "east,south",
          "4,2": "east,west",
          "4,3": "east,west",
          "4,4": "north,west",
          "4,5": "north,south",
          "5,0": "north,east",
          "5,1": "north,west",
          "5,2": "east,south",
          "5,3": "east,south,west",
          "5,4": "east,west",
          "5,5": "north,west"
        }
    },
    "bottom,right,top,left,stair,crossroad": {
        "fileName": "bottom,right,top,left,stair,crossroad",
        "north": true,
        "east": true,
        "south": true,
        "west": true,
        "others": "stair,crossroad",
        "map": {
          "0,0": "east,south",
          "0,1": "south,west",
          "0,2": "north,east,south",
          "0,3": "north,south,west",
          "0,4": "east,south",
          "0,5": "south,west",
          "1,0": "north,east",
          "1,1": "north,east,south,west",
          "1,2": "north,east,west",
          "1,3": "north,east,west",
          "1,4": "north,east,south,west",
          "1,5": "north,west",
          "2,0": "east,south,west",
          "2,1": "north,south,west",
          "2,2": "east,south",
          "2,3": "east,south,west",
          "2,4": "north,east,south,west",
          "2,5": "east,south,west",
          "3,0": "north,east,west",
          "3,1": "north,south,west",
          "3,2": "north,east",
          "3,3": "north,east,west",
          "3,4": "north,east,south,west",
          "3,5": "north,east,west",
          "4,0": "east,south",
          "4,1": "north,east,south,west",
          "4,2": "east,south,west",
          "4,3": "east,south,west",
          "4,4": "north,east,south,west",
          "4,5": "south,west",
          "5,0": "north,east",
          "5,1": "north,west",
          "5,2": "north,east,south",
          "5,3": "north,south,west",
          "5,4": "north,east",
          "5,5": "north,west"
        }
    },
    "bottom,right,top,left,deadend": {
        "fileName": "bottom,right,top,left,deadend",
        "north": true,
        "east": true,
        "south": true,
        "west": true,
        "others": "deadend",
        "map": {

        }
    },
    "bottom,right,top,left,stairs": {
        "fileName": "bottom,right,top,left,stairs",
        "north": true,
        "east": true,
        "south": true,
        "west": true,
        "others": "stairs,crossroad",
        "map": {
          "0,2": "north,east,south",
          "0,3": "north,south,west",
          "1,1": "east,south",
          "1,2": "north,east,west",
          "1,3": "north,east,west",
          "1,4": "south,west",
          "2,0": "east,south,west",
          "2,1": "north,south,west",
          "2,2": "east,south",
          "2,3": "south,west",
          "2,4": "north,east,south",
          "2,5": "east,south,west",
          "3,0": "north,east,west",
          "3,1": "north,south,west",
          "3,2": "north",
          "3,3": "north,south",
          "3,4": "north,east,south",
          "3,5": "north,east,west",
          "4,1": "north,east",
          "4,2": "east,south,west",
          "4,3": "north,east,south,west",
          "4,4": "north,west",
          "5,2": "north,east,south",
          "5,3": "north,south,west"
        }
    },
    "bottom,right,top,left,crooked,crossroad5": {
        "fileName": "bottom,right,top,left,crooked,crossroad5",
        "north": true,
        "east": true,
        "south": true,
        "west": true,
        "others": "crooked,crossroad",
        "map": {

        }
    },
    "bottom,right,top,left,crooked,crossroad6": {
        "fileName": "bottom,right,top,left,crooked,crossroad6",
        "north": true,
        "east": true,
        "south": true,
        "west": true,
        "others": "crooked,crossroad",
        "map": {
          "0,2": "north,east,south,ne",
          "0,3": "north,south,west,nw,se",
          "2,0": "east,south,west,se,sw",
          "2,1": "south,west,se,sw",
          "1,4": "se,nw",
          "2,5": "east,south,se,nw",
          "3,0": "north,east,west,ne,nw",
          "3,1": "north,east,west,se,nw",
          "3,2": "south,west,se,nw",
          "3,5": "north,east,south,ne,sw",
          "4,2": "north,east,south,se,nw",
          "4,3": "east,south,west,se,sw,nw",
          "4,4": "east,south,west,ne,se,sw",
          "4,5": "north,south,west,ne,sw",
          "5,2": "north,east,south,ne,se",
          "5,3": "north,east,south,west,ne,sw,nw",
          "5,4": "north,east,west,ne,nw,sw",
          "5,5": "north,west,nw"
        }
    },
    "bottom,right,top,passage": {
        "fileName": "bottom,right,top,passage",
        "north": true,
        "east": true,
        "south": true,
        "west": false,
        "others": "passage",
        "map": {
          "0,2": "north,east,south",
          "0,3": "north,south,west",
          "1,2": "north,east,south",
          "1,3": "north,south,west",
          "2,2": "north,east,south",
          "2,3": "north,east,south,west",
          "2,4": "east,south,west",
          "2,5": "east,south,west",
          "3,2": "north,east,south",
          "3,3": "north,east,south,west",
          "3,4": "north,east,west",
          "3,5": "north,east,west",
          "4,2": "north,east,south",
          "4,3": "north,south,west",
          "5,2": "north,east,south",
          "5,3": "north,south,west"
        }
    },
    "bottom,right,top,stairs1": {
        "fileName": "bottom,right,top,stairs1",
        "north": true,
        "east": true,
        "south": true,
        "west": false,
        "others": "stairs",
        "map": {
          "0,2": "north,east,south",
          "0,3": "north,west",
          "1,2": "north,south",
          "2,0": "south",
          "2,2": "north,south",
          "2,4": "east,south",
          "2,5": "east,south,west",
          "3,0": "north,south",
          "3,2": "north,south",
          "3,4": "north,east,south",
          "3,5": "north,east,west",
          "4,0": "north,east",
          "4,1": "east,west",
          "4,2": "north,east,south,west",
          "4,3": "east,south,west",
          "4,4": "north,west",
          "5,2": "north,east,south",
          "5,3": "north,south,west"
        }
    },
   "bottom,right,top,passage1": {
        "fileName": "bottom,right,top,passage1",
        "north": true,
        "east": true,
        "south": true,
        "west": false,
        "others": "passage",
        "map": {
          "0,2": "north,east,south",
          "0,3": "north,south,west",
          "1,1": "east,south",
          "1,2": "north,east,west",
          "1,3": "north,east,west",
          "1,4": "south,west",
          "2,1": "north,south",
          "2,4": "north,east,south",
          "2,5": "east,south,west",
          "3,1": "north,south",
          "3,4": "north,east,south",
          "3,5": "north,east,west",
          "4,1": "north,east",
          "4,2": "east,south,west",
          "4,3": "east,south,west",
          "4,4": "north,west",
          "5,2": "north,east,south",
          "5,3": "north,south,west"
        }
    },
   "bottom,right,top,passage2": {
        "fileName": "bottom,right,top,passage2",
        "north": true,
        "east": true,
        "south": true,
        "west": false,
        "others": "passage,empty",
        "map": {
          "0,2": "north,east,south",
          "0,3": "north,south,west",
          "1,1": "east,south",
          "1,2": "north,east,south,west",
          "1,3": "north,east,south,west",
          "1,4": "south,west",
          "2,1": "north,east,south",
          "2,2": "north,east,south,west",
          "2,3": "north,east,south,west",
          "2,4": "north,east,south,west",
          "2,5": "east,south,west",
          "3,1": "north,east,south",
          "3,2": "north,east,south,west",
          "3,3": "north,east,south,west",
          "3,4": "north,east,south,west",
          "3,5": "north,east,west",
          "4,1": "north,east",
          "4,2": "north,east,south,west",
          "4,3": "north,east,south,west",
          "4,4": "north,west",
          "5,2": "north,east,south",
          "5,3": "north,south,west",
        }
    },
   "bottom,right,top,stairs": {
        "fileName": "bottom,right,top,stairs",
        "north": true,
        "east": true,
        "south": true,
        "west": false,
        "others": "stairs",
        "map": {
          "0,2": "north,east,south",
          "0,3": "north,south,west",
          "1,1": "south",
          "1,2": "north,south",
          "1,3": "north,east",
          "1,4": "south,west",
          "2,1": "north,south",
          "2,2": "north,east,south",
          "2,3": "west",
          "2,4": "north,east,south",
          "2,5": "east,south,west",
          "3,1": "north,south",
          "3,2": "north,east",
          "3,3": "west",
          "3,4": "north,east,south",
          "3,5": "north,east,west",
          "4,1": "north,east",
          "4,2": "east,south,west",
          "4,3": "east,south,west",
          "4,4": "north,west",
          "5,2": "north,east,south",
          "5,3": "north,south,west"
        }
    },
    "bottom,right,top,fire": {
        "fileName": "bottom,right,top,fire",
        "north": true,
        "east": true,
        "south": true,
        "west": false,
        "others": "fire",
        "map": {
          "0,2": "north,east,south",
          "0,3": "north,south,west",
          "1,1": "east,south",
          "1,2": "north,east,west",
          "1,3": "north,east,west",
          "1,4": "south,west",
          "2,1": "north,south",
          "2,4": "north,east,south",
          "2,5": "east,south,west",
          "3,1": "north,south",
          "3,4": "north,east,south",
          "3,5": "north,east,west",
          "4,1": "north,east",
          "4,2": "east,south,west",
          "4,3": "east,south,west",
          "4,4": "north,west",
          "5,2": "north,east,south",
          "5,3": "north,south,west",
        }
    },
    "bottom,right,top,lava": {
        "fileName": "bottom,right,top,lava",
        "north": true,
        "east": true,
        "south": true,
        "west": false,
        "others": "lava",
        "map": {
            "0,2": "north,east,south",
            "0,3": "north,south,west",
            "1,2": "north,east,south",
            "1,3": "north,east,south,west",
            "1,4": "south,west",
            "2,1": "east,south",
            "2,2": "north,east,south,west",
            "2,3": "north,east,south,west",
            "2,4": "north,east,south,west",
            "2,5": "east,south,west",
            "3,1": "north,east",
            "3,2": "north,east,south,west",
            "3,3": "north,east,south,west",
            "3,4": "north,east,south,west",
            "3,5": "north,east,west",
            "4,2": "north,east,south",
            "4,3": "north,east,south,west",
            "4,4": "north,west",
            "5,2": "north,east,south",
            "5,3": "north,south,west",
        }
    },
    "bottom,right,top,maze": {
        "fileName": "bottom,right,top,maze",
        "north": true,
        "east": true,
        "south": true,
        "west": false,
        "others": "maze",
        "map": {
          "0,0": "east,south",
          "0,1": "east,south,west",
          "0,2": "north,east,west",
          "0,3": "north,west",
          "1,0": "north,east,south",
          "1,1": "north,south,west",
          "2,0": "north,east",
          "2,1": "north,east,west",
          "2,2": "east,west",
          "2,3": "east,west",
          "2,4": "east,west",
          "2,5": "east,south,west",
          "3,0": "east,south",
          "3,1": "east,south,west",
          "3,2": "east,west",
          "3,3": "east,west",
          "3,4": "east,west",
          "3,5": "north,east,west",
          "4,0": "north,east,south",
          "4,1": "north,south,west",
          "5,0": "north,east",
          "5,1": "north,east,west",
          "5,2": "east,south,west",
          "5,3": "south,west"
        }
    },
    "bottom,right,top,room": {
        "fileName": "bottom,right,top,room",
        "north": true,
        "east": true,
        "south": true,
        "west": false,
        "others": "room",
        "map": {
            "0,2": "north,east,south", //exit - right
            "0,3": "north,south,west", //Exit - left
            "1,0": "east,south",
            "1,1": "east,south,west",
            "1,2": "north,east,south,west",
            "1,3": "north,east,south,west",
            "1,4": "south,west",
            "2,0": "north,east,south",
            "2,1": "north,east,south,west",
            "2,2": "north,east,south,west",
            "2,3": "north,east,south,west",
            "2,4": "north,east,south,west",
            "2,5": "east,south,west",
            "3,0": "north,east,south",
            "3,1": "north,east,south,west",
            "3,2": "north,east,south,west",
            "3,3": "north,east,south,west",
            "3,4": "north,east,south,west",
            "3,5": "north,east,west",
            "4,0": "north,east",
            "4,1": "north,east,west",
            "4,2": "north,east,south,west",
            "4,3": "north,east,south,west",
            "4,4": "north,west",
            "5,2": "north,east,south",
            "5,3": "north,south,west"
        }
    },

    "bottom,right,left,room": {
        "fileName": "bottom,right,left,room",
        "north": false,
        "east": true,
        "south": true,
        "west": true,
        "others": "room",
        "map": {
          "0,1": "east,south,se",
          "0,2": "east,south,west,se,sw",
          "0,3": "east,south,west,se,sw",
          "0,4": "south,west,sw",
          "1,1": "north,east,south,ne,sw",
          "1,2": "north,east,south,west,ne,se,sw,nw",
          "1,3": "north,east,south,west,ne,se,sw,nw",
          "1,4": "north,south,west,se,sw,nw",
          "2,0": "east,south,west,ne,se,sw",
          "2,1": "north,east,south,west,ne,se,sw",
          "2,2": "north,east,south,west,ne,se,sw,nw",
          "2,3": "north,east,south,west,ne,se,sw,nw",
          "2,4": "north,east,south,west,se,sw,nw",
          "2,5": "east,south,west,se,sw,nw",
          "3,0": "north,east,west,ne,se,nw",
          "3,1": "north,east,south,west,ne,se,nw",
          "3,2": "north,east,south,west,ne,se,sw,nw",
          "3,3": "north,east,south,west,ne,se,sw,nw",
          "3,4": "north,east,south,west,ne,sw,nw",
          "3,5": "north,east,west,ne,sw,nw",
          "4,1": "north,east,ne,se,nw",
          "4,2": "north,east,south,west,ne,se,nw",
          "4,3": "north,east,south,west,ne,sw,nw",
          "4,4": "north,west,ne,sw,nw",
          "5,2": "north,east,south,ne,se,nw",
          "5,3": "north,south,west,ne,sw,nw",
        }
    },
    "bottom,right,left,passage": {
        "fileName": "bottom,right,left,passage",
        "north": false,
        "east": true,
        "south": true,
        "west": true,
        "others": "passage",
        "map": {
          "2,0": "east,south,west",
          "3,0": "north,east,west",
          "2,1": "east,south,west",
          "3,1": "north,east,west",
          "2,2": "east,south,west",
          "3,2": "north,east,south,west",
          "2,3": "east,south,west",
          "3,3": "north,east,south,west",
          "2,4": "east,south,west",
          "3,4": "north,east,west",
          "2,5": "east,south,west",
          "3,5": "north,east,west",
          "4,2": "north,east,south",
          "4,3": "north,south,west",
          "5,2": "north,east,south",
          "5,3": "north,south,west"
        }
    },
    "bottom,right,left,passage1": {
        "fileName": "bottom,right,left,passage1",
        "north": false,
        "east": true,
        "south": true,
        "west": true,
        "others": "passage",
        "map": {
          "1,1": "east,south",
          "1,2": "east,west",
          "1,3": "east,west",
          "1,4": "south,west",
          "2,0": "east,south,west",
          "2,1": "north,south,west",
          "2,4": "north,east,south",
          "2,5": "north,east,west",
          "3,0": "north,east,west",
          "3,1": "north,south,west",
          "3,4": "north,east,south",
          "3,5": "north,east,west",
          "4,1": "north,east",
          "4,2": "east,south,west",
          "4,3": "east,south,west",
          "4,4": "north,west",
          "5,2": "north,east,south",
          "5,3": "north,south,west"
        }
    },
    "bottom,right,left,passage2": {
        "fileName": "bottom,right,left,passage2",
        "north": false,
        "east": true,
        "south": true,
        "west": true,
        "others": "passage,empty",
        "map": {
          "1,1": "east,south",
          "1,2": "east,south,west",
          "1,3": "east,south,west",
          "1,4": "south,west",
          "2,0": "east,south,west",
          "2,1": "north,east,south,west",
          "2,2": "north,east,south,west",
          "2,3": "north,east,south,west",
          "2,4": "north,east,south,west",
          "2,5": "south,west",
          "3,0": "north,east,west",
          "3,1": "north,east,south,west",
          "3,2": "north,east,south,west",
          "3,3": "north,east,south,west",
          "3,4": "north,east,south,west",
          "3,5": "north,east,west",
          "4,1": "north,east",
          "4,2": "north,east,south,west",
          "4,3": "north,east,south,west",
          "4,4": "north,west",
          "5,2": "north,east,south",
          "5,3": "north,south,west"
        }
    },
    "bottom,right,left,fire": {
        "fileName": "bottom,right,left,fire",
        "north": false,
        "east": true,
        "south": true,
        "west": true,
        "others": "fire",
        "map": {
          "1,1": "east,south",
          "1,2": "east,west",
          "1,3": "east,west",
          "1,4": "south,west",
          "2,0": "east,south,west",
          "2,1": "north,south,west",
          "2,4": "north,east,south",
          "2,5": "east,south,west",
          "3,0": "north,east,west",
          "3,1": "north,south,west",
          "3,4": "north,east,south",
          "3,5": "north,east,west",
          "4,1": "north,east",
          "4,2": "east,south,west",
          "4,3": "east,south,west",
          "4,4": "north,west",
          "5,2": "north,east,south",
          "5,3": "north,south,west"
        }
    },
/*    "bottom,right,left,lava": {
        "fileName": "bottom,right,left,lava",
        "north": false,
        "east": true,
        "south": true,
        "west": true,
        "others": "lava"
    },
*/
    "bottom,right,left,maze": {
        "fileName": "bottom,right,left,maze",
        "north": false,
        "east": true,
        "south": true,
        "west": true,
        "others": "maze",
        "map": {
          "0,0": "east,south",
          "0,1": "east,south,west",
          "0,2": "south,west",
          "0,3": "east,south",
          "0,4": "east,south,west",
          "0,5": "south,west",
          "1,0": "north,east,south",
          "1,1": "north,east,west",
          "1,2": "north,south,west",
          "1,3": "north,east,south",
          "1,4": "north,east,west",
          "1,5": "north,south,west",
          "2,0": "north,south,west",
          "2,2": "north,south",
          "2,3": "north,south",
          "2,5": "north,east,south",
          "3,0": "north,west",
          "3,2": "north,south",
          "3,3": "north,south",
          "3,5": "north,east",
          "4,2": "north,south",
          "4,3": "north,south",
          "5,2": "north,east,south",
          "5,3": "north,south,west",
        }
    },

    "bottom,right,left,stairs": {
        "fileName": "bottom,right,left,stairs",
        "north": false,
        "east": true,
        "south": true,
        "west": true,
        "others": "stairs",
        "map": {
          "1,1": "east",
          "1,2": "east,west",
          "1,3": "east,west",
          "1,4": "south,west",
          "2,0": "east,south,west",
          "2,1": "east,west",
          "2,2": "east,south,west",
          "2,3": "south,west",
          "2,4": "north,east,south",
          "2,5": "east,south,west",
          "3,0": "north,east,west",
          "3,1": "south,west",
          "3,2": "north",
          "3,3": "north",
          "3,4": "north,east,south",
          "3,5": "north,east,west",
          "4,1": "north,east",
          "4,2": "east,south,west",
          "4,3": "east,south,west",
          "4,4": "north,west",
          "5,2": "north,east,south",
          "5,3": "north,south,west"
        }
    },
    "bottom,right,left,stairs1": {
        "fileName": "bottom,right,left,stairs1",
        "north": false,
        "east": true,
        "south": true,
        "west": true,
        "others": "stairs",
        "map": {
          "0,2": "east",
          "0,3": "east,west",
          "0,4": "south,west",
          "1,4": "north,south",
          "2,0": "east,south,west",
          "2,1": "east,west",
          "2,2": "east,west",
          "2,3": "east,west",
          "2,4": "north,east,south,west",
          "2,5": "east,south,west",
          "3,0": "north,east,west",
          "3,1": "north,west",
          "3,4": "north,east,south",
          "3,5": "north,east,west",
          "4,2": "east,south",
          "4,3": "east,south,west",
          "4,4": "north,west",
          "5,2": "north,east,south",
          "5,3": "north,south,west"
        }
    },
    "bottom,top,pipes": {
        "fileName": "bottom,top,pipes",
        "north": true,
        "east": false,
        "south": true,
        "west": false,
        "others": "pipes",
        "map": {
          "0,2": "north,east,south",
          "0,3": "north,south,west",
          "1,1": "east,south",
          "1,2": "north,east,west",
          "1,3": "north,east,west",
          "1,4": "south,west",
          "2,1": "north,south",
          "2,4": "north,south",
          "3,1": "north,south",
          "3,4": "north,south",
          "4,1": "north,east",
          "4,2": "east,south,west",
          "4,3": "east,south,west",
          "4,4": "north,west",
          "5,2": "north,east,south",
          "5,3": "north,south,west"
        }
    },
    "bottom,top,trap1": {
        "fileName": "bottom,top,trap1",
        "north": true,
        "east": false,
        "south": true,
        "west": false,
        "others": "trap",
        "map": {

        }
    },
    "bottom,top,trap2": {
        "fileName": "bottom,top,trap2",
        "north": true,
        "east": false,
        "south": true,
        "west": false,
        "others": "trap",
        "map": {
          "0,2": "north,east,south",
          "0,3": "north,south,west",
          "1,2": "north,east,south",
          "1,3": "north,south,west",
          "2,2": "north,east,south",
          "2,3": "north,south,west",
          "3,2": "north,east,south",
          "3,3": "north,south,west",
          "4,2": "north,east,south",
          "4,3": "north,south,west",
          "5,2": "north,east,south",
          "5,3": "north,south,west",
        }
    },
    "bottom,top,items": {
        "fileName": "bottom,top,items",
        "north": true,
        "east": false,
        "south": true,
        "west": false,
        "others": "items",
        "map": {
          "0,2": "north,east,south",
          "0,3": "north,south,west",
          "1,0": "east,south",
          "1,1": "east,west",
          "1,2": "north,east,south,west",
          "1,3": "north,south,west",
          "1,4": "east,south",
          "1,5": "south,west",
          "2,0": "north,south",
          "2,1": "south",
          "2,2": "north,east,south",
          "2,3": "north,south,west",
          "2,4": "north,east",
          "2,5": "north,south,west",
          "3,0": "north,east",
          "3,1": "north,west,south",
          "3,2": "north,east,south",
          "3,3": "north,south,west",
          "3,5": "north,south",
          "4,1": "north",
          "4,2": "north,east,south",
          "4,3": "north,east,south,west",
          "4,4": "east,west",
          "4,5": "north,west",
          "5,2": "north,east,south",
          "5,3": "north,south,west",
        }
    },
    "bottom,top,pool": {
        "fileName": "bottom,top,pool",
        "north": true,
        "east": false,
        "south": true,
        "west": false,
        "others": "pool",
        "map": {
          "0,2": "north,east,south",
          "0,3": "north,south,west",
          "1,2": "north,east,south",
          "1,3": "north,south,west",
          "2,2": "north,east,south",
          "2,3": "north,south,west",
          "3,2": "north,east,south",
          "3,3": "north,south,west",
          "4,2": "north,east,south",
          "4,3": "north,south,west",
          "5,2": "north,east,south",
          "5,3": "north,south,west",
        }
    },
    "bottom,top,pit": {
        "fileName": "bottom,top,pit",
        "north": true,
        "east": false,
        "south": true,
        "west": false,
        "others": "pit",
        "map": {
          "0,2": "north,east,south",
          "0,3": "north,south,west",
          "1,1": "east,south",
          "1,4": "south,west",
          "2,1": "north,south",
          "2,4": "north,south",
          "3,1": "north,south",
          "3,4": "north,south",
          "4,1": "north,east",
          "4,2": "east,south,west",
          "4,3": "east,south,west",
          "4,4": "north,west",
          "5,2": "north,east,south",
          "5,3": "north,south,west"
        }
    },
    "bottom,top,pit1": {
        "fileName": "bottom,top,pit1",
        "north": true,
        "east": false,
        "south": true,
        "west": false,
        "others": "pit",
        "map": {

        }
    },
    "bottom,top,pit3": {
        "fileName": "bottom,top,pit3",
        "north": true,
        "east": false,
        "south": true,
        "west": false,
        "others": "pit",
        "map": {

        }
    },

    "bottom,top,trophies": {
        "fileName": "bottom,top,trophies",
        "north": true,
        "east": false,
        "south": true,
        "west": false,
        "others": "trophies",
        "map": {
          "0,2": "north,east,south",
          "0,3": "north,south,west",
          "1,2": "north,east,south",
          "1,3": "north,south,west",
          "2,2": "north,east,south",
          "2,3": "north,south,west",
          "3,2": "north,east,south",
          "3,3": "north,south,west",
          "4,2": "north,east,south",
          "4,3": "north,south,west",
          "5,2": "north,east,south",
          "5,3": "north,south,west",
        }
    },
    "bottom,top,empty": {
        "fileName": "bottom,top,empty",
        "north": true,
        "east": false,
        "south": true,
        "west": false,
        "others": "empty",
        "map": {

        }
    },
    "bottom,top,crooked,passage3": {
        "fileName": "bottom,top,crooked,passage3",
        "north": true,
        "east": false,
        "south": true,
        "west": false,
        "others": "crooked,passage",
        "map": {
          "0,2": "north,east,south",
          "0,3": "north,west",
          "1,2": "north,south",
          "2,1": "east",
          "2,2": "north,east,west",
          "2,3": "east,south,west",
          "2,4": "west",
          "3,3": "north,south",
          "4,1": "east",
          "4,2": "east,south,west",
          "4,3": "north,east,south,west",
          "4,4": "west",
          "5,2": "north,east,south",
          "5,3": "north,south,west"
        }
    },
    "bottom,top,passage1": {
        "fileName": "bottom,top,passage1",
        "north": true,
        "east": false,
        "south": true,
        "west": false,
        "others": "passage",
        "map": {
          "0,2": "north,east,south",
          "0,3": "north,south,west",
          "1,2": "north,east,south",
          "1,3": "north,south,west",
          "2,2": "north,east,south",
          "2,3": "north,south,west",
          "3,2": "north,east,south",
          "3,3": "north,south,west",
          "4,2": "north,east,south",
          "4,3": "north,south,west",
          "5,2": "north,east,south",
          "5,3": "north,south,west",
        }
    },
    "bottom,top,passage2": {
        "fileName": "bottom,top,passage2",
        "north": true,
        "east": false,
        "south": true,
        "west": false,
        "others": "passage",
        "map": {
          "0,2": "north,east,south",
          "0,3": "north,south,west",
          "1,2": "north,east,south",
          "1,3": "north,east,south,west",
          "1,4": "west",
          "2,1": "east,south",
          "2,2": "north,east,south,west",
          "2,3": "north,south,west",
          "3,1": "north,east",
          "3,2": "north,east,south,west",
          "3,3": "north,east,south,west",
          "3,4": "south,west",
          "4,2": "north,east,south",
          "4,3": "north,east,south,west",
          "4,4": "north,west",
          "5,2": "north,east,south",
          "5,3": "north,south,west"
        }
    },
    "bottom,top,passage3": {
        "fileName": "bottom,top,passage3",
        "north": true,
        "east": false,
        "south": true,
        "west": false,
        "others": "passage",
        "map": {

        }
    },
    "bottom,top,passage": {
        "fileName": "bottom,top,passage",
        "north": true,
        "east": false,
        "south": true,
        "west": false,
        "others": "passage",
        "map": {
          "0,2": "north,east,south",
          "0,3": "north,south,west",
          "1,2": "north,east,south",
          "1,3": "north,south,west",
          "2,2": "north,east,south",
          "2,3": "north,south,west",
          "3,2": "north,east,south",
          "3,3": "north,south,west",
          "4,2": "north,east,south",
          "4,3": "north,south,west",
          "5,2": "north,east,south",
          "5,3": "north,south,west",
        }
    },
    "right,coffins": {
        "fileName": "right,coffins",
        "north": false,
        "east": true,
        "south": false,
        "west": false,
        "others": "coffins",
        "map": {
          "1,1": "south",
          "2,1": "north,east,south",
          "2,2": "south,west",
          "2,5": "east,south",
          "3,1": "north,east",
          "3,2": "north,east,west",
          "3,3": "east,west",
          "3,4": "east,west",
          "3,5": "north,east,west"
        }
    },
    "right,room": {
        "fileName": "right,room",
        "north": false,
        "east": true,
        "south": false,
        "west": false,
        "others": "room",
        "map": {
          "2,3": "east,south",
          "2,4": "east,south,west",
          "2,5": "east,south,west",
          "3,3": "north,east",
          "3,4": "north,east,west",
          "3,5": "north,east,west",
        }
    },
    "right,room1": {
        "fileName": "right,room1",
        "north": false,
        "east": true,
        "south": false,
        "west": false,
        "others": "room",
        "map": {

        }
    },
    "right,room2": {
        "fileName": "right,room2",
        "north": false,
        "east": true,
        "south": false,
        "west": false,
        "others": "room",
        "map": {

        }
    },
 	"right,deadend": {
        "fileName": "right,deadend",
        "north": false,
        "east": true,
        "south": false,
        "west": false,
        "others": "deadend",
        "map": {

        }
    },
    "right,altar": {
        "fileName": "right,altar",
        "north": false,
        "east": true,
        "south": false,
        "west": false,
        "others": "altar",
        "map": {

        }
    },
    "right,left,trap2": {
        "fileName": "right,left,trap2",
        "north": false,
        "east": true,
        "south": false,
        "west": true,
        "others": "trap",
        "map": {
          "2,0": "east,south,west",
          "3,0": "north,east,west",
          "2,1": "east,south,west",
          "3,1": "north,east,west",
          "2,2": "east,south,west",
          "3,2": "north,east,west",
          "2,3": "east,south,west",
          "3,3": "north,east,west",
          "2,4": "east,south,west",
          "3,4": "north,east,west",
          "2,5": "east,south,west",
          "3,5": "north,east,west",
        }
    },
    "right,left,trap3": {
        "fileName": "right,left,trap3",
        "north": false,
        "east": true,
        "south": false,
        "west": true,
        "others": "trap",
        "map": {

        }
    },
    "right,left,pool": {
        "fileName": "right,left,pool",
        "north": false,
        "east": true,
        "south": false,
        "west": true,
        "others": "pool",
        "map": {
          "2,0": "east,south,west",
          "3,0": "north,east,west",
          "2,1": "east,south,west",
          "3,1": "north,east,west",
          "2,2": "east,south,west",
          "3,2": "north,east,west",
          "2,3": "east,south,west",
          "3,3": "north,east,west",
          "2,4": "east,south,west",
          "3,4": "north,east,west",
          "2,5": "east,south,west",
          "3,5": "north,east,west",
        }
    },
    "right,left,pit1": {
        "fileName": "right,left,pit1",
        "north": false,
        "east": true,
        "south": false,
        "west": true,
        "others": "pit",
        "map": {

        }
    },
    "right,left,pit2": {
        "fileName": "right,left,pit2",
        "north": false,
        "east": true,
        "south": false,
        "west": true,
        "others": "pit",
        "map": {
          "2,0": "",
          "5,2": "east,south",
          "5,3": "north,east"
        }
    },
    "right,left,pipes": {
        "fileName": "right,left,pipes",
        "north": false,
        "east": true,
        "south": false,
        "west": true,
        "others": "pipes",
        "map": {
          "1,1": "east,south",
          "1,2": "east,west",
          "1,3": "east,west",
          "1,4": "south,west",
          "2,0": "east,south,west",
          "2,1": "north,south,west",
          "2,4": "north,east,south",
          "2,5": "east,south,west",
          "3,0": "north,east,west",
          "3,1": "north,south,west",
          "3,4": "north,east,south",
          "3,5": "north,east,west",
          "4,1": "north,east",
          "4,2": "east,west",
          "4,3": "east,west",
          "4,4": "north,west"
        }
    },
    "right,left,items": {
        "fileName": "right,left,items",
        "north": false,
        "east": true,
        "south": false,
        "west": true,
        "others": "items",
        "map": {

        }
    },
    "right,left,passage": {
        "fileName": "right,left,passage",
        "north": false,
        "east": true,
        "south": false,
        "west": true,
        "others": "passage,empty",
        "map": {
          "2,0": "east,south,west",
          "3,0": "north,east,west",
          "2,1": "east,south,west",
          "3,1": "north,east,west",
          "2,2": "east,south,west",
          "3,2": "north,east,west",
          "2,3": "east,south,west",
          "3,3": "north,east,west",
          "2,4": "east,south,west",
          "3,4": "north,east,west",
          "2,5": "east,south,west",
          "3,5": "north,east,west",
        }
    },
    "right,left,passage1": {
        "fileName": "right,left,passage1",
        "north": false,
        "east": true,
        "south": false,
        "west": true,
        "others": "passage",
        "map": {
          "2,0": "east,south,west",
          "3,0": "north,east,west",
          "2,1": "east,south,west",
          "3,1": "north,east,west",
          "2,2": "east,south,west",
          "3,2": "north,east,west",
          "2,3": "east,south,west",
          "3,3": "north,east,west",
          "2,4": "east,south,west",
          "3,4": "north,east,west",
          "2,5": "east,south,west",
          "3,5": "north,east,west",
        }
    },
    "right,left,passage2": {
        "fileName": "right,left,passage2",
        "north": false,
        "east": true,
        "south": false,
        "west": true,
        "others": "passage",
        "map": {

        }
    },
    "right,left,passage3": {
        "fileName": "right,left,passage3",
        "north": false,
        "east": true,
        "south": false,
        "west": true,
        "others": "passage",
        "map": {
          "1,1": "east,south",
          "1,2": "east,west",
          "1,3": "east,west",
          "1,4": "south,west",
          "2,0": "east,south,west",
          "2,1": "north,south,west",
          "2,4": "north,east,south",
          "2,5": "east,south,west",
          "3,0": "north,east,west",
          "3,1": "north,south,west",
          "3,4": "north,east",
          "3,5": "north,east,west",
          "4,1": "north"
        }
    },
    "right,left,trophies": {
        "fileName": "right,left,trophies",
        "north": false,
        "east": true,
        "south": false,
        "west": true,
        "others": "trophies",
        "map": {
          "2,0": "east,south,west",
          "3,0": "north,east,west",
          "2,1": "east,south,west",
          "3,1": "north,east,west",
          "2,2": "east,south,west",
          "3,2": "north,east,west",
          "2,3": "east,south,west",
          "3,3": "north,east,west",
          "2,4": "east,south,west",
          "3,4": "north,east,west",
          "2,5": "east,south,west",
          "3,5": "north,east,west",
        }
    },
    "right,left,crooked,passage3": {
        "fileName": "right,left,crooked,passage3",
        "north": false,
        "east": true,
        "south": false,
        "west": true,
        "others": "crooked,passage",
        "map": {

        }
    },
    "filler": {
        "fileName": "filler",
        "north": false,
        "east": false,
        "south": false,
        "west": false,
        "others": "filler",
        "map": {

        }
    },
    "filler1": {
        "fileName": "filler1",
        "north": false,
        "east": false,
        "south": false,
        "west": false,
        "others": "filler",
        "map": {

        }
    },
    "filler,water": {
        "fileName": "filler,water",
        "north": false,
        "east": false,
        "south": false,
        "west": false,
        "others": "filler,water",
        "map": {

        }
    },
    "bottom,entrance,bigroom": {
        "fileName": "bottom,entrance,bigroom",
        "north": false,
        "east": false,
        "south": true,
        "west": false,
        "others": "entrance,bigroom",
        "map": {

        }
    },
    "bottom,right,corner,bigroom": {
        "fileName": "bottom,right,corner,bigroom",
        "north": false,
        "east": true,
        "south": true,
        "west": false,
        "others": "corner,bigroom",
        "map": {

        }
    },
    "bottom,left,corner,bigroom": {
        "fileName": "bottom,left,corner,bigroom",
        "north": false,
        "east": false,
        "south": true,
        "west": true,
        "others": "corner,bigroom",
        "map": {

        }
    },
    "bottom,right,corner,bigroom,crooked": {
        "fileName": "bottom,right,corner,bigroom,crooked",
        "north": false,
        "east": true,
        "south": true,
        "west": false,
        "others": "corner,bigroom,crooked",
        "map": {

        }
    },
    "bottom,left,corner,bigroom,crooked1": {
        "fileName": "bottom,left,corner,bigroom,crooked1",
        "north": false,
        "east": false,
        "south": true,
        "west": true,
        "others": "corner,bigroom,crooked",
        "map": {

        }
    },
    "bottom,left,right,corner,bigroom,open": {
        "fileName": "bottom,left,right,corner,bigroom,open",
        "north": false,
        "east": true,
        "south": true,
        "west": true,
        "others": "corner,bigroom,open",
        "map": {

        }
    },
    "center,bigroom,stairs": {
        "fileName": "center,bigroom,stairs",
        "north": false,
        "east": false,
        "south": false,
        "west": false,
        "others": "center,bigroom,stairs",
        "map": {

        }
    },
    "center,bigroom,lava": {
        "fileName": "center,bigroom,lava",
        "north": false,
        "east": false,
        "south": false,
        "west": false,
        "others": "center,bigroom,lava",
        "map": {

        }
    },
    "center,bigroom,magic": {
        "fileName": "center,bigroom,magic",
        "north": false,
        "east": false,
        "south": false,
        "west": false,
        "others": "center,bigroom,magic",
        "map": {

        }
    },
    "center,bigroom": {
        "fileName": "center,bigroom",
        "north": false,
        "east": false,
        "south": false,
        "west": false,
        "others": "center,bigroom, empty",
        "map": {

        }
    },
    "center,bigroom, dias": {
        "fileName": "center,bigroom,dias",
        "north": false,
        "east": false,
        "south": false,
        "west": false,
        "others": "center,bigroom, dias",
        "map": {

        }
    },
    "right,top,corner,bigroom,deadend": {
        "fileName": "right,top,corner,bigroom,deadend",
        "north": true,
        "east": true,
        "south": false,
        "west": false,
        "others": "corner,bigroom,deadend",
        "map": {

        }
    },
    "right,top,left,corner,bigroom,open": {
        "fileName": "right,top,corner,bigroom,open",
        "north": true,
        "east": true,
        "south": false,
        "west": false,
        "others": "corner,bigroom,open",
        "map": {

        }
    },
    "right,entrance,bigroom": {
        "fileName": "right,entrance,bigroom",
        "north": false,
        "east": true,
        "south": false,
        "west": false,
        "others": "entrance,bigroom",
        "map": {

        }
    },
    "top,entrance,bigroom": {
        "fileName": "top,entrance,bigroom",
        "north": true,
        "east": false,
        "south": false,
        "west": false,
        "others": "entrance,bigroom",
        "map": {

        }
    },
    "top,entrance,bigroom,ornate": {
        "fileName": "top,entrance,bigroom,ornate",
        "north": true,
        "east": false,
        "south": false,
        "west": false,
        "others": "entrance,bigroom,ornate",
        "map": {

        }
    },
    "left,entrance,bigroom,ornate": {
        "fileName": "left,entrance,bigroom,ornate",
        "north": false,
        "east": false,
        "south": false,
        "west": true,
        "others": "entrance,bigroom,open",
        "map": {

        }
    },
    "left,entrance,bigroom,open": {
        "fileName": "left,entrance,bigroom,open",
        "north": false,
        "east": false,
        "south": false,
        "west": true,
        "others": "entrance,bigroom,open",
        "map": {

        }
    },
    "left,entrance,bigroom,deadend,ornate": {
        "fileName": "left,entrance,bigroom,deadend,ornate",
        "north": false,
        "east": false,
        "south": false,
        "west": true,
        "others": "entrance,bigroom,deadend,ornate",
        "map": {

        }
    },
    "top,left,corner,bigroom": {
        "fileName": "top,left,corner,bigroom",
        "north": true,
        "east": false,
        "south": false,
        "west": true,
        "others": "corner,bigroom",
        "map": {

        }
    },
    "overlay,chests" : {
        "fileName": "overlay,chests",
        "north": false,
        "east": false,
        "south": false,
        "west": false,
        "others": "overlay,chests",
        "map": {

        }
    }
}

overlayTiles = {
    "overlay,trap,snakes" : {
        "fileName": "overlay,trap,snakes",
        "north": false,
        "east": false,
        "south": false,
        "west": false,
        "class": "snakePit",
        "others": "overlay,trap,snakes"
    },
    "overlay,trap,snakes2" : {
        "fileName": "overlay,trap,snakes2",
        "north": false,
        "east": false,
        "south": false,
        "west": false,
        "class": "snakePit",
        "others": "overlay,trap,snakes"
    },
    "overlay,chests" : {
        "fileName": "overlay,chests",
        "north": false,
        "east": false,
        "south": false,
        "west": false,
        "class": "chests1",
        "others": "overlay,chests"
    },
    "overlay,passage" : {
        "fileName": "overlay,passage",
        "north": false,
        "east": false,
        "south": false,
        "west": false,
        "class": "passage",
        "others": "overlay,passage"
    },
    "overlay,corner,statue" : {
    "fileName": "overlay,corner,statue",
    "north": false,
    "east": false,
    "south": false,
    "west": false,
    "class": "cornerStatue",
    "others": "overlay,corner,statue"
    }
}
